dist: focal  # ubuntu 20.04
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
   - "nightly"
   - "pypy3"
install:
  - pip install flake8 mypy
script:
  - python setup.py build install
  - flake8 ib_insync
  - mypy -p ib_insync
